apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: infrastructure-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./gitops/monitoring/controllers/lab
  prune: true
  healthChecks:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: grafana-admin
      namespace: monitoring
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: prometheus-basic-auth
      namespace: monitoring
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: kube-prometheus-stack
      namespace: monitoring
