apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-operator.yaml
  - external-secrets.yaml
  - flux-controllers.yaml
  - flux-operator.yaml
  - nvidia-dcgm-exporter.yaml
  - traefik.yaml
  - vault-metrics-service.yaml
  - vault.yaml
