apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Vendored from rancher/local-path-provisioner v0.0.36.
resources:
  - namespace.yaml
  - storage-class.yaml
  - service-account.yaml
  - role.yaml
  - cluster-role.yaml
  - role-binding.yaml
  - cluster-role-binding.yaml
  - config-map.yaml
  - deployment.yaml
