apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-server-kubelet-ca
  namespace: kube-system
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDEDCCAfigAwIBAgIIUTn40ZAgfOQwDQYJKoZIhvcNAQELBQAwJjEkMCIGA1UE
    AwwbdGFsb3MtOXh5LXpoYi1jYUAxNzg2MzI3MTcxMB4XDTI2MDgxMDAwNTkzMVoX
    DTI3MDgxMDAwNTkzMVowJjEkMCIGA1UEAwwbdGFsb3MtOXh5LXpoYi1jYUAxNzg2
    MzI3MTcxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzonnFPHU4zR1
    C60aByXA0EgACDmDpHiETUwSAjVbbCQoGmPz1OV5ACC/ATSgaLwNgeMCTC19lAJm
    s8VUnuGLE0rAlEhRknQneOcP8tXJn6XJJHPwi6uIdvGbmtz0PdaVzbES0953UGkP
    w5JIHpBlOQMy2LvEMhP5lfxdFzZl90hl7/r8i356sWTb8wihrM4+HZQDAmm2sR3+
    hVZV28wVo0uJekl851FN2JudQcG8C9PACxiwjAKkfVcPcF/mXaLcxCFW5TtvTiYy
    rBdQ6a3IfecCDwkerI6dwPxwAt7q6S4uBNzCSbuzEax5pMbwsUZdQj43kzfnF/Az
    ddUhTTRHiQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUbssQzcrSdBSG/SfjvazaC5UNOjcwDQYJKoZIhvcNAQELBQAD
    ggEBAAzLKIh6MzFZmuCS+H8PYC8buh3NvmlCuF8qDeQ1HlyJ2YaNgcyBzcIgxY6E
    oz6Ed8KM81elIJrabMvekFw/KfMtWRlapD4UvFu2T1m4y11U4jSEM2uwIskKGZE8
    +TtEbZjm1ReNsKi8KHUzy6gb9xbV8r+hOA9pbmoLS1Hec9Fu48aSvkJDqtFSLS68
    uMQ816xwEtb67XlfW4UabH7ycu8kGo7MtmFJI171ovM+k/dGXJdHLJVLJhQ21dmt
    +LvLgVJnzUHzVDQEzvqMCSYt56638B6zwOfzvUZVGlpoizhZ5AtT1qVE7HWKl2v2
    Xa/2ys5gwvqvHfCEST3BtRJVEKI=
    -----END CERTIFICATE-----
