apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/kube-prometheus-stack/

configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
