- resources:
    # backend: resources
    expanded: true
    cpu: true
    memory: true
    network: default
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: Homelab
    nodes:
      show: false
- openmeteo:
    label: Jagatsinghpur
    latitude: 20.2557
    longitude: 86.17112
    timezone: Asia/Kolkata
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 1
- datetime:
    text_size: 3xl
    format:
      hourCycle: h23
      timeStyle: short
