apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postiz
  namespace: postiz
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postiz-app
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .jwtSecret }}"
        DATABASE_URL: "postgresql://postiz:{{ .postizDatabasePassword }}@postiz-postgres-rw.postiz.svc.cluster.local:5432/postiz"
        REDIS_URL: "redis://:{{ .redisPassword }}@postiz-redis.postiz.svc.cluster.local:6379"
        LINKEDIN_CLIENT_ID: "{{ .linkedinClientId }}"
        LINKEDIN_CLIENT_SECRET: "{{ .linkedinClientSecret }}"
  data:
    - secretKey: jwtSecret
      remoteRef:
        key: postiz
        property: jwt-secret
    - secretKey: postizDatabasePassword
      remoteRef:
        key: postiz
        property: postiz-database-password
    - secretKey: redisPassword
      remoteRef:
        key: postiz
        property: redis-password
    - secretKey: linkedinClientId
      remoteRef:
        key: postiz
        property: linkedin-client-id
    - secretKey: linkedinClientSecret
      remoteRef:
        key: postiz
        property: linkedin-client-secret
