apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postiz-redis
  namespace: postiz
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postiz-redis
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: postiz
        property: redis-password
