apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postiz-temporal-database
  namespace: postiz
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postiz-temporal-database
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: temporal
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: postiz
        property: temporal-database-password
