apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postiz-temporal
  namespace: postiz
spec:
  name: temporal
  owner: temporal
  cluster:
    name: postiz-postgres
  databaseReclaimPolicy: retain
