# https://developer.hashicorp.com/vault/docs/deploy/kubernetes

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
  - ../../base/vault/
  - persistentVolume.yaml
  - persistentVolumeClaim.yaml

configMapGenerator:
  - name: vault-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
