apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-external-secret
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cloudflared-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cloudflared/tunnel
        property: token
