apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cloudflared-credentials
    creationPolicy: Owner
  data:
    - secretKey: credentials-file
      remoteRef:
        key: secret/data/cloudflared/tunnel
        property: credentials-file
    - secretKey: tunnel-id
      remoteRef:
        key: secret/data/cloudflared/tunnel
        property: tunnel-id
