apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  url: https://ritvikcs.github.io/homepage-helm/
  interval: 5m
  chart:
    spec:
      chart: homepage
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: homepage
        namespace: homepage
  values:
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "*"
