hostNetwork: false
ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.homelab.internal`)
    entryPoints:
      - web
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
