apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cloudflared
    creationPolicy: Owner
  data:
    - secretKey: credentials-file
      remoteRef:
        key: secret/data/cloudflared/tunnel
        property: credentials-file
    - secretKey: tunnel-id
      remoteRef:
        key: secret/data/cloudflared/tunnel
        property: tunnel-id
