vars: {
  d2-config: {
    theme-id: 300
    # sketch: true
    layout-engine: elk
    pad: 25
  }
}

direction: right

classes: {
  default: {
    style: {
      border-radius: 10
      fill: transparent
    }
  }
  platform: {
    style: {
      border-radius: 10
    }
  }
  runtime: {
    style: {
      border-radius: 10
    }
  }
  note: {
    style: {
      border-radius: 10
      stroke-dash: 4
    }
  }
  edge_default: {
    style.animated: true
    style.bold: true
    style.stroke: black
    style.fill: black
    style.font-color: white
  }
}

workstation: {
  label: "Workstation"
  class: default
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/windows-11.png
}

github: {
  label: "GitHub"
  class: default
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/github.svg
}

lan: {
  label: "LAN"
  class: default
}

lenovo: {
  label: "Lenovo"
  class: platform
  icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/lenovo.svg

  talos: {
    label: "Talos"
    class: runtime
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/talos.svg
  }

  kubernetes: {
    label: "Kubernetes"
    class: platform
    icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/kubernetes.svg

    cni: {
      label: "Core"
      class: runtime
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/coredns.svg
    }

    flux: {
      label: "Flux"
      class: runtime
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/flux-cd.svg
    }

    metallb: {
      label: "MetalLB"
      class: runtime
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/metallb.svg
    }

    traefik: {
      label: "Traefik"
      class: runtime
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/traefik.svg
    }

    homepage: {
      label: "Homepage"
      class: runtime
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homepage.png
    }

    gpu: {
      label: "GPU"
      class: runtime
      icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/nvidia.svg
    }
  }
}

workstation -> lan: "hosts"
lan -> lenovo.kubernetes.traefik: "192.168.0.60"
github -> lenovo.kubernetes.flux: "sync"
lenovo.talos -> lenovo.kubernetes: "runs"
lenovo.kubernetes.cni -> lenovo.kubernetes.traefik
lenovo.kubernetes.flux -> lenovo.kubernetes.metallb
lenovo.kubernetes.flux -> lenovo.kubernetes.traefik
lenovo.kubernetes.flux -> lenovo.kubernetes.homepage
lenovo.kubernetes.flux -> lenovo.kubernetes.gpu
lenovo.kubernetes.traefik -> lenovo.kubernetes.homepage: "route"
