apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-token-reviewer
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - pods
    verbs:
      - get
      - list
      - create
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - get
      - list
      - create
