apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  releaseName: traefik
  chartRef:
    kind: OCIRepository
    name: traefik-chart
    namespace: traefik
  install:
    createNamespace: false
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      valuesKey: values.yaml
