apiVersion: v1
kind: Service
metadata:
  name: linkding-service
  namespace: linkding
spec:
  selector:
    app: linkding
  ports:
    - protocol: TCP
      port: 9090
      targetPort: http
      name: http
  type: ClusterIP
