# https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
# https://cloudnative-pg.io/charts/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../base/cert-manager/

configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
