apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: prometheus-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: monitoring/prometheus
        property: users
