apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ocirepository.yaml
  - release.yaml

configMapGenerator:
  - name: nginx-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
