# https://artifacthub.io/packages/helm/bitnami/nginx

ingress:
  enabled: true
  hostname: nginx.homelab.internal

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
